apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xd2ygvdhw-go-gitops
  description: This is GitOps manifest for xd2ygvdhw-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=xd2ygvdhw-go
    backstage.io/kubernetes-id: xd2ygvdhw-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xd2ygvdhw-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xd2ygvdhw-go
